version: 0.1

phases:
  pre_build:
    commands:
      # Run all tests included with our application
      - go test ./... -v

  build:
    commands:
      # Build our application
      - go build -o application

artifacts:
  files:
    - application
