version: 0.1

phases:
  pre_build:
    commands:
      # Run all tests included with our application
      - pushd server && go test ./... -v && popd

  build:
    commands:
      # Build our application
      - pushd server && go build -o ../application && popd

artifacts:
  files:
    - "**/*"
